### ISSUE TITLE
MBT tests are failing (Ureq error: 404 for apalache-v0.11.0.jar)

### ISSUE THREAD

**Issue by hu55a1n1** [informalsystems/ibc-rs#1338]
## Crate
ibc 

## Summary of Bug
MBT tests are failing due to missing `.jar` file ->
```sh
$ cargo test --all-features --no-fail-fast -- --nocapture
# ...
     Running tests/mbt.rs (target/debug/deps/mbt-df1e65ab5015b576)

running 1 test

test mbt ... FAILED

failures:

---- mbt stdout ----
[modelator] Downloading model-checkers... 
thread 'mbt' panicked at 'Error while running modelator: Ureq error: https://github.com/informalsystems/modelator/raw/main/jars/apalache-v0.11.0.jar: status code 404', modules/tests/mbt.rs:11:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:515:5
   1: std::panicking::begin_panic_fmt
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:457:5
   2: mbt::mbt
             at ./modules/tests/mbt.rs:11:9
   3: mbt::mbt::{{closure}}
             at ./modules/tests/mbt.rs:7:1
   4: core::ops::function::FnOnce::call_once
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:227:5
   5: core::ops::function::FnOnce::call_once
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    mbt

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 52.11s
```

## Version
master

## Steps to Reproduce
```sh
$ cargo test --all-features --no-fail-fast -- --nocapture
```

## Acceptance Criteria
The MBT tests must pass.

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by rnbguy** [comment]
Sorry from the Modelator team. informalsystems/modelator#96 unfortunately overwritten the old Apalache jar. It should work now :)
