### ISSUE TITLE
Upgrade protos, upgrade gaiad in CI [Vega upgrade]

### ISSUE THREAD

**Issue by adizere** [informalsystems/ibc-rs#1408]
## Summary

Gaiad RC for 6.0.0 is out https://github.com/cosmos/gaia/releases/tag/v6.0.0-rc1

This is the first RC for Vega update, which will go live on the hub soon (should have been in Q3 2021).
https://github.com/cosmos/gaia/blob/main/docs/roadmap/cosmos-hub-roadmap-2.0.md#vega-upgrade-expected-q3-2021

## Proposal

We should prepare for 6.0.0:
- [ ] update our CI suite to use the new chain binary
- [ ] upgrade our generated .proto files to include [ibc-go 1.2](https://github.com/cosmos/ibc-go/blob/v1.2.0/CHANGELOG.md), with the associated compatibility fixes; for these fixes, it could be instructive to read on the [versioning discussion from the ibc-go repo](https://github.com/cosmos/ibc-go/discussions/409)

____

#### For Admin Use

- [x] Not duplicate issue
- [X] Appropriate labels applied
- [x] Appropriate milestone (priority) applied
- [x] Appropriate contributors tagged
- [X] Contributor assigned/self-assigned

**Comment by andynog** [comment]
Running the e2e test locally against gaia v6.0.0-rc2, the relayer test fails with:
````
{"timestamp":"2021-11-09T20:11:36.075264Z","level":"TRACE","fields":{"message":"[ibc-0 -> ibc-1:07-tendermint-1] finished misbehaviour verification after 5.074784876s"},"threadId":"ThreadId(22)"}
{"timestamp":"2021-11-09T20:11:36.130906Z","level":"TRACE","fields":{"message":"light client verification","trusted":"1-85","target":"1-96"},"threadId":"ThreadId(19)"}
{"timestamp":"2021-11-09T20:11:36.376720Z","level":"TRACE","fields":{"message":"light client verification","trusted":"1-78","target":"1-85"},"threadId":"ThreadId(19)"}
{"timestamp":"2021-11-09T20:11:36.624447Z","level":"TRACE","fields":{"message":"light client verification","trusted":"1-64","target":"1-78"},"threadId":"ThreadId(19)"}
{"timestamp":"2021-11-09T20:11:36.876632Z","level":"TRACE","fields":{"message":"light client verification","trusted":"1-61","target":"1-64"},"threadId":"ThreadId(19)"}
{"timestamp":"2021-11-09T20:11:37.105728Z","level":"TRACE","fields":{"message":"[ibc-1 -> ibc-0:07-tendermint-0] finished misbehaviour verification after 6.293314424s"},"threadId":"ThreadId(20)"}
2021-11-09 20:11:45 [   DEBUG] /usr/bin/hermes -c /relayer/simple_config.toml --json query channel end ibc-1 transfer channel-2
2021-11-09 20:11:45 [   DEBUG] {"result":{"connection_hops":["connection-1"],"ordering":"Unordered","remote":{"channel_id":null,"port_id":"transfer"},"state":"Init","version":"ics20-1"},"status":"success"}
2021-11-09 20:11:45 [   DEBUG] ChannelEnd(connection_hops=['connection-1'], ordering='Unordered', remote=Remote(channel_id=None, port_id='transfer'), state='Init', version='ics20-1')
2021-11-09 20:11:45 [   DEBUG] Status of channel end channel-2: ChannelEnd(connection_hops=['connection-1'], ordering='Unordered', remote=Remote(channel_id=None, port_id='transfer'), state='Init', version='ics20-1')

Traceback (most recent call last):
  File "/relayer/e2e/run.py", line 276, in <module>
    main()
  File "/relayer/e2e/run.py", line 262, in main
    channel.passive_channel_start_then_init(
  File "/relayer/e2e/e2e/channel.py", line 590, in passive_channel_start_then_init
    verify_state(c, ibc1, ibc0, ibc1_chan_id, port_id)
  File "/relayer/e2e/e2e/channel.py", line 565, in verify_state
    ibc0_chan_end = query_channel_end(c, ibc0, port_id, ibc0_chan_id)
  File "/relayer/e2e/e2e/channel.py", line 528, in query_channel_end
    res = cmd.run(c).success()
  File "/relayer/e2e/e2e/cmd.py", line 61, in run
    l.debug(' '.join(full_cmd))
TypeError: sequence item 9: expected str instance, NoneType found
```

not sure yet if it's the e2e setup or something with the gaia v6

**Comment by uhvyuhs77** [comment]
Sweet
