### ISSUE TITLE
Upgrade simapp files to run with latest simd

### ISSUE THREAD

**Issue by andynog** [informalsystems/ibc-rs#204]
Change simapp configuration to include more than one connection. This will allow properly testing of queries such as connections per client.

**Comment by andynog** [comment]
Tried to run `simd --home ./simapp/ start` using a compiled `simd` built from the latest `cosmos-sdk (master)` and it spits out an error. I believe it has to do with the proto changes. Our simapp files were generated before protobuf changes on cosmos-sdk. We need to regenerated the simapp folder using the latest simd.

```
simd --home ./simapp/ start
I[2020-10-07|17:30:57.973] starting ABCI with Tendermint                module=main 
panic: Any JSON doesn't have '@type'

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/codec.(*ProtoCodec).MustUnmarshalJSON(0xc001044330, 0xc000f44480, 0x10e, 0x120, 0x1eaabe0, 0xc000699d00)
	github.com/cosmos/cosmos-sdk/codec/proto_codec.go:150 +0x8a
github.com/cosmos/cosmos-sdk/x/auth.AppModule.InitGenesis(0x1ea01e0, 0xc0006b2ef0, 0x1ecfa20, 0xc001044330, 0x1ecfa20, 0xc001044330, 0xc000010178, 0x1ea01e0, 0xc0006b2f90, 0x1ea0260, ...)
	github.com/cosmos/cosmos-sdk/x/auth/module.go:139 +0xa4
github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(0xc000f3abd0, 0x1ebe4a0, 0xc000124030, 0x1ed30e0, 0xc000699bc0, 0x0, 0x0, 0xc00126a240, 0x8, 0x0, ...)
	github.com/cosmos/cosmos-sdk/types/module/module.go:306 +0x2b5
github.com/cosmos/cosmos-sdk/simapp.(*SimApp).InitChainer(0xc0000fc000, 0x1ebe4a0, 0xc000124030, 0x1ed30e0, 0xc000699bc0, 0x0, 0x0, 0xc00126a240, 0x8, 0x0, ...)
	github.com/cosmos/cosmos-sdk/simapp/app.go:454 +0x170
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc000602d80, 0x18188888, 0xed69708b8, 0x0, 0xc00126a240, 0x8, 0xc000f3f0a0, 0x2a15830, 0x0, 0x0, ...)
```

**Comment by adizere** [comment]
Superseded by #32 and the line of work for CI/end-to-end testing.
